### ISSUE TITLE
Data from paper

### ISSUE THREAD

**Issue by TalSchuster** [copenlu/fever-adversarial-attacks#1]
Interesting work!

Can you please share the set of 156 claims and respective evidence sentences from your paper?
Could be great for evaluating other models on them.

Thanks

**Comment by dwright37** [comment]
Thanks for your interest! We've just uploaded the claims (156 for triggers using the STSB objective, 156 without). You can find them under final_labelled_annotations.tsv. We also updated the README with a description of the columns.
