### ISSUE TITLE
No such file or directory when preparing dataset

### ISSUE THREAD

**Issue by QiuYuer** [copenlu/fever-adversarial-attacks#3]
Hi, when I tried to follow the steps in the README file, I failed at the dataset preparation. When I run the command: 

python scripts/create_nli_dataset.py --dataset_dirs data/paper_train.jsonl --wiki_dir data/wiki-pages/wiki-pages/ --output_paths data/train_sr_nli.jsonl , it says there is no such file or directory. 

I think the reason may be that I did not download the input data, but it is the first step in README, and I did not find where I can download the input data. Thus, could you help me figure this out?

Really appreciate your help!

**Comment by apepa** [comment]
Hi, there is a small clarification added in the README about the data. To be more elaborate -- this paper works with the FEVER dataset and you can get and use either the paper's or the shared task's splits as indicated on the FEVER's website https://fever.ai/data.html
