### ISSUE TITLE
Import Error:cannot import name 'GPT2FeverDataset

### ISSUE THREAD

**Issue by QiuYuer** [copenlu/fever-adversarial-attacks#4]
Hello,

I met the import error when making the GPT2 generated claims:

The detailed information about the error is:

`File "train_gpt2_model.py", line 16, in <module>
from datareader import GPT2FeverDataset 
ImportError: cannot import name 'GPT2FeverDataset`

However, I have already installed datareader by
`pip install datareader`
and I cannot find GPT2FeverDataset or datareader anywhere on GitHub. Thus, could you point out where GPT2FeverDataset or needed datareader come from?  

Thank you for your help!

**Comment by dwright37** [comment]
I had forgotten to add the datareader module to the repo. I just added it (datareader.py), can you try again and let us know if the issue is resolved?

**Comment by QiuYuer** [comment]
Hello, sorry for the delay. @dwright37 
I tried to run this, but it shows the error

`FileNotFoundError: [Errno 2] No such file or directory: './data/indomain_words.txt'`

I think there may be some missing files for this to run. Could you please upload this file too, or do we need to create it by ourselves?
Thank you for your help!

**Comment by dwright37** [comment]
We resolved this offline, the file should be there now.
