### ISSUE TITLE
Sharing prepared dataset

### ISSUE THREAD

**Issue by S-Abdelnabi** [copenlu/fever-adversarial-attacks#5]
Hi,

Thank you so much for releasing your code.
I am wondering whether you could please share the prepared dataset in step 1. I am having troubles running the Papelo system.

Thanks.

**Comment by apepa** [comment]
Hi, the readme has been updated with the corresponding link to the dataset ([https://huggingface.co/datasets/copenlu/fever_gold_evidence](https://huggingface.co/datasets/copenlu/fever_gold_evidence))
Please, note that if you want to use the dataset with the datasets API, you might need to install the latest version of the library (pip install git+https://github.com/huggingface/datasets.git@master)
